server:
  http_listen_port: 9009

target: all
multitenancy_enabled: false

limits:
  max_label_names_per_series: 100

ingester:
  ring:
    replication_factor: 1

distributor:
  ring:
    instance_addr: 127.0.0.1

blocks_storage:
  backend: filesystem
  filesystem:
    dir: /tmp/mimir/blocks

ruler_storage:
  backend: filesystem
  filesystem:
    dir: /tmp/mimir/rules

alertmanager_storage:
  backend: filesystem
  filesystem:
    dir: /tmp/mimir/alerts
